[kafka]
hosts = ["localhost:9092"]
consumer_group_id = "nn-fe"
client_id = "nn-fe"

[metrics]
[metrics.metric_type]
WeightVariance = "*-weight-variance-*"
Concavity = "*-concavity-*"
Loss = "*-loss-*"
[metrics.dim_type]
RadialCoordinate = ["-"]
[metrics.dim_axis]
Y = ["loss-*"]

[network]
[network.layer_type]
Normalization = ["1dNormalization", "2dNormalization"]
AttentionEncoder = ["TransformerEncoder"]
AttentionDecoder = ["TransformerEncoder"]
FullyConnected = ["Linear"]
